In [1]:
import numpy as np
import pandas as pd

from datetime import datetime

In [2]:
cd C:\Users\ic07949\desktop\BoH\Model\deposit

C:\Users\ic07949\desktop\BoH\Model\deposit

# 1. SAV

In [121]:
df_sav = pd.read_csv('df_sav.csv')

C:\Users\ic07949\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (27,29,34,37,40,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [123]:
df_sav.shape

(1996950, 48)

In [124]:
df_sav.columns

Index(['fileDate', 'applicationID', 'classCode', 'portfolio', 'accountNo',
       'branch', 'currentBal', 'aggrBalMTD', 'avgBalMTD', 'avgBalActive',
       'originationDate', 'lastRolloverDate', 'maturityDate', 'cdTerm',
       'interestRate', 'interestAccrBasis', 'respCode', 'rateIndex',
       'rateAdjuster', 'closedAcctFlag', 'closedDate', 'name1', 'productCode',
       'coNo', 'duration', 'ftpRate', 'ftpMo', 'eStatement', 'openedByCode',
       'openedByCodeDesc', 'productNo', 'intPaidTo', 'MTDMinBalAmt', 'NAICS',
       'bsaCode', 'ebbRestrictCode', 'Referral_Resp_Code',
       'Referral_Resp_Code_Description', 'ctp_relationshipUnit',
       'ctp_portfolioUnit', 'ctp_referringUnit', 'ctp_relationshipOfficer',
       'ctp_portfolioOfficer', 'ctp_referringOfficer', 'bsaRiskCode',
       'institutionalBanking', 'bsaActivityCode', 'value'],
      dtype='object')

In [163]:
df_sav_first = df_sav.groupby('accountNo').first().reset_index()

In [193]:
df_sav_first.shape

(89217, 48)

In [203]:
#filedate and origination date
df_sav_first['fileDate'] = pd.to_datetime(df_sav_first['fileDate'])
df_sav_first['originationDate'] = pd.to_datetime(df_sav_first['originationDate'])

df_sav_first['fileYM'] = df_sav_first['fileDate'].apply(lambda x: datetime.strftime(x, "%Y-%m"))
df_sav_first['originYM'] = df_sav_first['originationDate'].apply(lambda x: datetime.strftime(x, "%Y-%m"))

In [204]:
df_sav_first.groupby('fileDate').count()

,accountNo,applicationID,classCode,portfolio,branch,currentBal,aggrBalMTD,avgBalMTD,avgBalActive,originationDate,...,ctp_referringUnit,ctp_relationshipOfficer,ctp_portfolioOfficer,ctp_referringOfficer,bsaRiskCode,institutionalBanking,bsaActivityCode,value,fileYM,originYM
fileDate,,,,,,,,,,,,,,,,,,,,,
2007-12-31,17188,17188,17188,17188,17188,17188,17188,17188,17188,17188,...,0,0,0,0,122,0,19,17188,17188,17188
2008-01-31,475,475,475,475,475,475,475,475,475,475,...,0,0,0,0,1,0,0,475,475,475
2008-02-29,438,438,438,438,438,438,438,438,438,438,...,0,0,0,0,1,0,1,438,438,438
2008-03-31,243,243,243,243,243,243,243,243,243,243,...,0,0,0,0,3,0,1,243,243,243
2008-04-30,280,280,280,280,280,280,280,280,280,280,...,0,0,0,0,1,0,0,280,280,280
2008-05-31,323,323,323,323,323,323,323,323,323,323,...,0,0,0,0,0,0,0,323,323,323
2008-06-30,351,351,351,351,351,351,351,351,351,351,...,0,0,0,0,1,0,0,351,351,351
2008-07-31,352,352,352,352,352,352,352,352,352,352,...,0,0,0,0,1,0,0,352,352,352
2008-08-31,320,320,320,320,320,320,320,320,320,320,...,0,0,0,0,0,0,0,320,320,320
2008-09-30,656,656,656,656,656,656,656,656,656,656,...,0,0,0,0,0,0,0,656,656,656
2008-10-31,942,942,942,942,942,942,942,942,942,942,...,0,0,0,0,0,0,0,942,942,942
2008-11-30,768,768,768,768,768,768,768,768,768,768,...,0,0,0,0,0,0,0,768,768,768
2008-12-31,458,458,458,458,458,458,458,458,458,458,...,0,0,0,0,1,0,0,458,458,458
2009-01-31,526,526,526,526,526,526,526,526,526,526,...,0,0,0,0,1,0,0,526,526,526
2009-02-28,556,556,556,556,556,556,556,556,556,556,...,0,0,0,0,0,0,0,556,556,556
2009-03-31,423,423,423,423,423,423,423,423,423,423,...,0,0,0,0,0,0,0,423,423,423
2009-04-30,380,380,380,380,380,380,380,380,380,380,...,0,0,0,0,1,0,1,380,380,380
2009-05-31,344,344,344,344,344,344,344,344,344,344,...,0,0,0,0,0,0,0,344,344,344
2009-06-30,250,250,250,250,250,250,250,250,250,250,...,0,0,0,0,0,0,0,250,250,250
2009-07-31,255,255,255,255,255,255,255,255,255,255,...,0,0,0,0,0,0,0,255,255,255
2009-08-31,266,266,266,266,266,266,266,266,266,266,...,0,0,0,0,0,0,0,266,266,266
2009-09-30,233,233,233,233,233,233,233,233,233,233,...,0,0,0,0,0,0,0,233,233,233
2009-10-31,246,246,246,246,246,246,246,246,246,246,...,0,0,0,0,1,0,1,246,246,246
2009-11-30,224,224,224,224,224,224,224,224,224,224,...,0,0,0,0,2,0,0,224,224,224
2009-12-31,204,204,204,204,204,204,204,204,204,204,...,0,0,0,0,4,0,1,204,204,204
2010-01-31,300,300,300,300,300,300,300,300,300,300,...,0,0,0,0,0,0,0,300,300,300
2010-02-28,214,214,214,214,214,214,214,214,214,214,...,0,0,0,0,0,0,0,214,214,214
2010-03-31,384,384,384,384,384,384,384,384,384,384,...,0,0,0,0,1,0,0,384,384,384
2010-04-30,300,300,300,300,300,300,300,300,300,300,...,0,0,0,0,0,0,0,300,300,300
2010-05-31,313,313,313,313,313,313,313,313,313,313,...,0,0,0,0,1,0,1,313,313,313
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-09-30,284,284,284,284,284,284,284,284,284,284,...,0,0,0,0,111,0,0,284,284,284
2015-10-31,276,276,276,276,276,276,276,276,276,276,...,0,0,0,0,114,0,0,276,276,276
2015-11-30,233,233,233,233,233,233,233,233,233,233,...,0,0,0,0,117,0,0,233,233,233
2015-12-31,253,253,253,253,253,253,253,253,253,253,...,0,0,0,0,118,0,1,253,253,253
2016-01-31,365,365,365,365,365,365,365,365,365,365,...,0,0,0,0,176,0,0,365,365,365
2016-02-29,394,394,394,394,394,394,394,394,394,394,...,0,0,0,0,173,0,1,394,394,394
2016-03-31,330,330,330,330,330,330,330,330,330,330,...,0,0,0,0,169,0,1,330,330,330
2016-04-30,303,303,303,303,303,303,303,303,303,303,...,0,0,0,0,172,0,1,303,303,303
2016-05-31,261,261,261,261,261,261,261,261,261,261,...,0,0,0,0,123,0,1,261,261,261
2016-06-30,279,279,279,279,279,279,279,279,279,279,...,0,1,1,0,152,0,0,279,279,279
2016-07-31,268,268,268,268,268,268,268,268,268,268,...,0,0,0,0,154,0,2,268,268,268
2016-08-31,349,349,349,349,349,349,349,349,349,349,...,0,0,0,0,243,0,2,349,349,349
2016-09-30,249,249,249,249,249,249,249,249,249,249,...,0,0,0,0,197,0,1,249,249,249
2016-10-31,232,232,232,232,232,232,232,232,232,232,...,0,0,0,0,178,0,3,232,232,232
2016-11-30,8897,8897,8897,8897,8897,8897,8897,8897,8897,8897,...,9,14,13,9,733,1,52,8897,8897,8897
2016-12-31,285,285,285,285,285,285,285,285,285,285,...,0,0,0,0,229,0,2,285,285,285
2017-01-31,510,510,510,510,510,510,510,510,510,510,...,0,0,0,0,446,0,4,510,510,510
2017-02-28,362,362,362,362,362,362,362,362,362,362,...,0,0,0,0,325,0,5,362,362,362
2017-03-31,428,428,428,428,428,428,428,428,428,428,...,0,0,0,0,393,0,5,428,428,428
2017-04-30,326,326,326,326,326,326,326,326,326,326,...,0,0,0,0,308,0,3,326,326,326
2017-05-31,356,356,356,356,356,356,356,356,356,356,...,0,0,0,0,345,0,3,356,356,356
2017-06-30,363,363,363,363,363,363,363,363,363,363,...,0,0,0,0,359,0,3,363,363,363
2017-07-31,319,319,319,319,319,319,319,319,319,319,...,1,1,1,1,318,0,5,319,319,319
2017-08-31,378,378,378,378,378,378,378,378,378,378,...,0,0,0,0,378,0,6,378,378,378
2017-09-30,524,524,524,524,524,524,524,524,524,524,...,5,5,5,5,524,0,7,524,524,524
2017-10-31,760,760,760,760,760,760,760,760,760,760,...,507,709,710,513,760,0,7,760,760,760
2017-11-30,483,483,483,483,483,483,483,483,483,483,...,332,483,483,335,483,0,12,483,483,483
2017-12-31,387,387,387,387,387,387,387,387,387,387,...,251,387,387,254,387,0,4,387,387,387
2018-01-31,1377,1377,1377,1377,1377,1377,1377,1377,1377,1377,...,1050,1375,1375,1058,1377,0,15,1377,1377,1377
2018-02-28,1047,1047,1047,1047,1047,1047,1047,1047,1047,1047,...,809,1047,1047,816,1047,0,13,1047,1047,1047

In [206]:
df_sav_first_notnew = df_sav_first[df_sav_first['fileYM'] != df_sav_first['originYM']]

In [208]:
df_sav_first_notnew.shape

(46231, 50)

In [219]:
df_sav_first_notnew_count = df_sav_first_notnew.groupby('fileDate').count().reset_index()
df_sav_first_notnew_sum = df_sav_first_notnew.groupby('fileDate').sum().reset_index()

In [230]:
df_sav_first_notnew_count.to_csv('df_sav_first_notnew_count.csv')
df_sav_first_notnew_sum.to_csv('df_sav_first_notnew_sum.csv')

# 2. DDA

In [220]:
df_dda = pd.read_csv('df_dda.csv')

C:\Users\ic07949\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (12,27,29,34,37,38,39,40,41,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [221]:
df_dda.shape

(9945855, 48)

In [222]:
df_dda_first = df_dda.groupby('accountNo').first().reset_index()

In [223]:
df_dda_first.shape

(279655, 48)

In [224]:
#filedate and origination date
df_dda_first['fileDate'] = pd.to_datetime(df_dda_first['fileDate'])
df_dda_first['originationDate'] = pd.to_datetime(df_dda_first['originationDate'])

df_dda_first['fileYM'] = df_dda_first['fileDate'].apply(lambda x: datetime.strftime(x, "%Y-%m"))
df_dda_first['originYM'] = df_dda_first['originationDate'].apply(lambda x: datetime.strftime(x, "%Y-%m"))

In [225]:
df_dda_first.groupby('fileDate').count()

,accountNo,applicationID,classCode,portfolio,branch,currentBal,aggrBalMTD,avgBalMTD,avgBalActive,originationDate,...,ctp_referringUnit,ctp_relationshipOfficer,ctp_portfolioOfficer,ctp_referringOfficer,bsaRiskCode,institutionalBanking,bsaActivityCode,value,fileYM,originYM
fileDate,,,,,,,,,,,,,,,,,,,,,
2007-12-31,42619,42619,42619,42619,42619,42619,42619,42619,42619,42619,...,2,3,3,2,1759,0,296,42619,42619,42619
2008-01-31,509,509,509,509,509,509,509,509,509,509,...,0,0,0,0,12,0,1,509,509,509
2008-02-29,886,886,886,886,886,886,886,886,886,886,...,0,0,0,0,18,0,3,886,886,886
2008-03-31,535,535,535,535,535,535,535,535,535,535,...,0,0,0,0,24,0,9,535,535,535
2008-04-30,525,525,525,525,525,525,525,525,525,525,...,0,0,0,0,18,0,7,525,525,525
2008-05-31,458,458,458,458,458,458,458,458,458,458,...,0,0,0,0,20,0,2,458,458,458
2008-06-30,512,512,512,512,512,512,512,512,512,512,...,0,0,0,0,25,0,6,512,512,512
2008-07-31,505,505,505,505,505,505,505,505,505,505,...,0,0,0,0,24,0,3,505,505,505
2008-08-31,872,872,872,872,872,872,872,872,872,872,...,0,0,0,0,26,0,4,872,872,872
2008-09-30,1367,1367,1367,1367,1367,1367,1367,1367,1367,1367,...,0,0,0,0,46,0,8,1367,1367,1367
2008-10-31,1168,1168,1168,1168,1168,1168,1168,1168,1168,1168,...,0,0,0,0,64,0,17,1168,1168,1168
2008-11-30,793,793,793,793,793,793,793,793,793,793,...,0,0,0,0,49,0,9,793,793,793
2008-12-31,701,701,701,701,701,701,701,701,701,701,...,0,0,0,0,27,0,6,701,701,701
2009-01-31,644,644,644,644,644,644,644,644,644,644,...,0,0,0,0,39,0,9,644,644,644
2009-02-28,594,594,594,594,594,594,594,594,594,594,...,0,0,0,0,20,0,9,594,594,594
2009-03-31,807,807,807,807,807,807,807,807,807,807,...,1,1,1,1,41,0,17,807,807,807
2009-04-30,633,633,633,633,633,633,633,633,633,633,...,0,0,0,0,24,0,6,633,633,633
2009-05-31,758,758,758,758,758,758,758,758,758,758,...,0,0,0,0,18,0,3,758,758,758
2009-06-30,619,619,619,619,619,619,619,619,619,619,...,0,0,0,0,31,0,8,619,619,619
2009-07-31,586,586,586,586,586,586,586,586,586,586,...,0,0,0,0,26,0,10,586,586,586
2009-08-31,510,510,510,510,510,510,510,510,510,510,...,0,0,0,0,20,0,3,510,510,510
2009-09-30,543,543,543,543,543,543,543,543,543,543,...,0,0,0,0,38,0,8,543,543,543
2009-10-31,481,481,481,481,481,481,481,481,481,481,...,0,0,0,0,28,0,5,481,481,481
2009-11-30,429,429,429,429,429,429,429,429,429,429,...,0,0,0,0,20,0,6,429,429,429
2009-12-31,508,508,508,508,508,508,508,508,508,508,...,0,0,0,0,32,0,8,508,508,508
2010-01-31,454,454,454,454,454,454,454,454,454,454,...,0,0,0,0,26,0,6,454,454,454
2010-02-28,411,411,411,411,411,411,411,411,411,411,...,0,0,0,0,23,0,2,411,411,411
2010-03-31,689,689,689,689,689,689,689,689,689,689,...,0,0,0,0,36,0,11,689,689,689
2010-04-30,586,586,586,586,586,586,586,586,586,586,...,0,0,0,0,20,0,7,586,586,586
2010-05-31,414,414,414,414,414,414,414,414,414,414,...,0,0,0,0,19,0,2,414,414,414
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-09-30,1236,1236,1236,1236,1236,1236,1236,1236,1236,1236,...,1,3,3,1,826,0,20,1236,1236,1236
2015-10-31,1156,1156,1156,1156,1156,1156,1156,1156,1156,1156,...,1,1,1,1,809,0,15,1156,1156,1156
2015-11-30,966,966,966,966,966,966,966,966,966,966,...,0,0,0,0,647,0,17,966,966,966
2015-12-31,1093,1093,1093,1093,1093,1093,1093,1093,1093,1093,...,1,2,2,1,805,0,25,1093,1093,1093
2016-01-31,873,873,873,873,873,873,873,873,873,873,...,3,3,3,3,645,0,18,873,873,873
2016-02-29,949,949,949,949,949,949,949,949,949,949,...,4,5,5,4,706,0,15,949,949,949
2016-03-31,929,929,929,929,929,929,929,929,929,929,...,2,3,3,2,695,0,23,929,929,929
2016-04-30,1345,1345,1345,1345,1345,1345,1345,1345,1345,1345,...,0,1,1,0,1027,0,27,1345,1345,1345
2016-05-31,1265,1265,1265,1265,1265,1265,1265,1265,1265,1265,...,1,1,1,1,990,0,37,1265,1265,1265
2016-06-30,1325,1325,1325,1325,1325,1325,1325,1325,1325,1325,...,0,0,0,0,1039,0,24,1325,1325,1325
2016-07-31,965,965,965,965,965,965,965,965,965,965,...,1,3,3,1,763,0,17,965,965,965
2016-08-31,3054,3054,3054,3054,3054,3054,3054,3054,3054,3054,...,6,9,9,6,1317,0,94,3054,3054,3054
2016-09-30,1060,1060,1060,1060,1060,1060,1060,1060,1060,1060,...,1,3,3,1,884,0,20,1060,1060,1060
2016-10-31,836,836,836,836,836,836,836,836,836,836,...,2,3,3,2,717,0,25,836,836,836
2016-11-30,48434,48434,48434,48434,48434,48434,48434,48434,48434,48434,...,150,260,268,152,8550,0,868,48434,48434,48434
2016-12-31,1211,1211,1211,1211,1211,1211,1211,1211,1211,1211,...,3,3,3,3,1063,0,23,1211,1211,1211
2017-01-31,1508,1508,1508,1508,1508,1508,1508,1508,1508,1508,...,1,1,1,1,1362,0,29,1508,1508,1508
2017-02-28,1241,1241,1241,1241,1241,1241,1241,1241,1241,1241,...,0,2,2,0,1160,0,34,1241,1241,1241
2017-03-31,1429,1429,1429,1429,1429,1429,1429,1429,1429,1429,...,4,4,4,4,1321,0,57,1429,1429,1429
2017-04-30,1212,1212,1212,1212,1212,1212,1212,1212,1212,1212,...,2,2,2,2,1144,0,25,1212,1212,1212
2017-05-31,1261,1261,1261,1261,1261,1261,1261,1261,1261,1261,...,2,3,3,2,1219,0,26,1261,1261,1261
2017-06-30,1271,1271,1271,1271,1271,1271,1271,1271,1271,1271,...,2,3,3,2,1234,0,34,1271,1271,1271
2017-07-31,1222,1222,1222,1222,1222,1222,1222,1222,1222,1222,...,2,4,4,2,1217,0,31,1222,1222,1222
2017-08-31,1448,1448,1448,1448,1448,1448,1448,1448,1448,1448,...,3,3,3,3,1448,8,31,1448,1448,1448
2017-09-30,1239,1239,1239,1239,1239,1239,1239,1239,1239,1239,...,4,5,5,4,1239,6,17,1239,1239,1239
2017-10-31,1268,1268,1268,1268,1268,1268,1268,1268,1268,1268,...,830,1191,1189,834,1268,3,30,1268,1268,1268
2017-11-30,1123,1123,1123,1123,1123,1123,1123,1123,1123,1123,...,793,1123,1123,801,1123,3,30,1123,1123,1123
2017-12-31,1233,1233,1233,1233,1233,1233,1233,1233,1233,1233,...,861,1216,1216,868,1229,6,31,1233,1233,1233
2018-01-31,1637,1637,1637,1637,1637,1637,1637,1637,1637,1637,...,1193,1630,1630,1202,1637,4,49,1637,1637,1637
2018-02-28,1367,1367,1367,1367,1367,1367,1367,1367,1367,1367,...,1034,1366,1366,1041,1367,0,45,1367,1367,1367

In [227]:
df_dda_first_notnew = df_dda_first[df_dda_first['fileYM'] != df_dda_first['originYM']]

In [228]:
df_dda_first_notnew.shape

(161898, 50)

In [229]:
df_dda_first_notnew_count = df_dda_first_notnew.groupby('fileDate').count().reset_index()
df_dda_first_notnew_sum =df_dda_first_notnew.groupby('fileDate').sum().reset_index()

In [231]:
df_dda_first_notnew_count.to_csv('df_dda_first_notnew_count.csv')
df_dda_first_notnew_sum.to_csv('df_dda_first_notnew_sum.csv')